name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          tools-deps: latest
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Run linters
        run: clojure -Srepro -J-Dclojure.main.report=stderr -T:build lint
