name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Java LTS
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          tools-deps: latest

      - name: Run linters
        run: clojure -Srepro -J-Dclojure.main.report=stderr -T:build lint
